// Generated by Selenium IDE

import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.HashMap;
import java.util.Map;
public class FailtoLoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver","C:\\Users\\Admin\\Coding_Projects\\Selenium\\Selenium Intro\\Gecko\\geckodriver.exe");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void failtoLogin() {
    driver.get("https://www.amazon.co.uk/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.cssSelector("#nav-signin-tooltip .nav-action-inner")).click();
    driver.findElement(By.id("ap_email")).sendKeys("test");
    driver.findElement(By.id("authportal-main-section")).click();
    driver.findElement(By.cssSelector(".a-button-inner > #continue")).click();
    Assert.assertTrue(driver.findElement(By.cssSelector(".a-alert-heading")).getText() == "There was a problem");
  }
}
