// Generated by Selenium IDE
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.HashMap;
import java.util.Map;
public class Test2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver","C:\\Users\\Admin\\Coding_Projects\\Selenium\\Selenium Intro\\Gecko\\geckodriver.exe");

    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test2() {
    driver.get("https://www.amazon.co.uk/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    {
      WebElement element = driver.findElement(By.cssSelector(".nav-long-width"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebDriverWait wait = new WebDriverWait(driver, 300);
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("#nav-flyout-ya-signin .nav-action-inner")));
    }
    driver.findElement(By.cssSelector("#nav-flyout-ya-signin .nav-action-inner")).click();
    driver.findElement(By.id("ap_email")).sendKeys("test");
    driver.findElement(By.cssSelector(".a-button-inner > #continue")).click();
    Assert.assertTrue(driver.findElement(By.cssSelector(".a-alert-heading")).getText() == "There was a problem");
  }
}
